# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.example.com    
    Template:
      Count: 30     
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org2: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: Org2
    Domain: org2.example.com
    Template:
      Count: 30
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Org3: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: Org3
    Domain: org3.example.com
    Template:
      Count: 30
    Users:
      Count: 1

  - Name: Org4
    Domain: org4.example.com
    Template:
      Count: 30
    Users:
      Count: 1

  - Name: Org5
    Domain: org5.example.com
    Template:
      Count: 30
    Users:
      Count: 1

  - Name: Org6
    Domain: org6.example.com
    Template:
      Count: 30
    Users:
      Count: 1

  - Name: Org7
    Domain: org7.example.com
    Template:
      Count: 30
    Users:
      Count: 1

  - Name: Org8
    Domain: org8.example.com
    Template:
      Count: 30
    Users:
      Count: 1

  - Name: Org9
    Domain: org9.example.com
    Template:
      Count: 30
    Users:
      Count: 1

  - Name: Org10
    Domain: org10.example.com
    Template:
      Count: 30
    Users:
      Count: 1





