---
test:
  name: smallbank
  description: 400-800
  clients:
    type: local
    number: 10
  rounds:
  - label: open
    txNumber:
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 400
    - type: fixed-rate
      opts:
        tps: 420
    - type: fixed-rate
      opts:
        tps: 440
    - type: fixed-rate
      opts:
        tps: 460
    - type: fixed-rate
      opts:
        tps: 480
    - type: fixed-rate
      opts:
        tps: 500
    - type: fixed-rate
      opts:
        tps: 520
    - type: fixed-rate
      opts:
        tps: 540
    - type: fixed-rate
      opts:
        tps: 560
    - type: fixed-rate
      opts:
        tps: 580
    - type: fixed-rate
      opts:
        tps: 600
    - type: fixed-rate
      opts:
        tps: 620
    - type: fixed-rate
      opts:
        tps: 640
    - type: fixed-rate
      opts:
        tps: 660
    - type: fixed-rate
      opts:
        tps: 680
    - type: fixed-rate
      opts:
        tps: 700
    - type: fixed-rate
      opts:
        tps: 720
    - type: fixed-rate
      opts:
        tps: 740
    - type: fixed-rate
      opts:
        tps: 760
    - type: fixed-rate
      opts:
        tps: 780
    - type: fixed-rate
      opts:
        tps: 800
    arguments:
      accounts: 50000
      txnPerBatch: 1
    callback: benchmark/smallbank/smallbankOperations.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1

