---
test:
  name: simple
  description: Exp 1. 10 rounds. 2000 tr. 200 tps to 2000 tps. Performance with simple account opening.
  clients:
    type: local
    number: 10
  rounds:
  - label: open
    txNumber:
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 400
    - type: fixed-rate
      opts:
        tps: 600
    - type: fixed-rate
      opts:
        tps: 800
    - type: fixed-rate
      opts:
        tps: 1000
    - type: fixed-rate
      opts:
        tps: 1200
    - type: fixed-rate
      opts:
        tps: 1400
    - type: fixed-rate
      opts:
        tps: 1600
    - type: fixed-rate
      opts:
        tps: 1800
    - type: fixed-rate
      opts:
        tps: 2000
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
