---
test:
  name: simple
  description: 100-1200
  clients:
    type: local
    number: 10
  rounds:
  - label: open
    txNumber:
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    - 5000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 200
    - type: fixed-rate
      opts:
        tps: 300
    - type: fixed-rate
      opts:
        tps: 400
    - type: fixed-rate
      opts:
        tps: 500
    - type: fixed-rate
      opts:
        tps: 600
    - type: fixed-rate
      opts:
        tps: 700
    - type: fixed-rate
      opts:
        tps: 800
    - type: fixed-rate
      opts:
        tps: 900
    - type: fixed-rate
      opts:
        tps: 1000
    - type: fixed-rate
      opts:
        tps: 1100
    - type: fixed-rate
      opts:
        tps: 1200
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
